name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build release
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags=" -s" -o dist/jd_ck_selenium_macos_amd64
          GOOS=darwin GOARCH=arm64  go build -ldflags=" -s" -o dist/jd_ck_selenium_macos_arm64
          GOOS=linux GOARCH=amd64  go build -ldflags=" -s" -o dist/jd_ck_selenium_linux_amd64
          GOOS=windows GOARCH=amd64  go build -ldflags="-H windowsgui -s" -o dist/jd_ck_selenium_windows_amd64.exe
          GOOS=windows GOARCH=386  go build -ldflags="-H windowsgui -s" -o dist/jd_ck_selenium_windows_i386.exe

      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: jd_ck_selenium
          path: dist/*